### ISSUE TITLE
Path parameter

### ISSUE THREAD

**Issue by mightyiam** [lomirus/live-server#2]
Hey, thank you for authoring this, @lomirus . Could you please add an argument to specify the path of the root being served?

**Comment by lomirus** [comment]
Sounds like a good idea. I think it can be added in the next version in few days.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by lomirus** [comment]
v0.4.0 has been published: https://github.com/lomirus/live-server/releases/tag/v0.4.0
