### ISSUE TITLE
Can't find html file when using the path parameter

### ISSUE THREAD

**Issue by mightyiam** [lomirus/live-server#3]
I get
```
[ERROR] Failed to read "./index.html": could not read file `./index.html`
```

When running without the path parameter from inside the path it works fine.

**Comment by lomirus** [comment]
Oh sorry, I just updated the watcher but forgot to update the server path 😅.  v0.4.1 will fix it soon.

**Comment by lomirus** [comment]
Updated. Try it.

**Comment by mightyiam** [comment]
Seems to work. Thank you.
