### ISSUE TITLE
Fails to read TTF files

### ISSUE THREAD

**Issue by thecre8tor** [lomirus/live-server#5]
I am trying to serve a ttf file and I am getting: 
```
[ERROR] Failed to read "/home/alexander/ultron/open-source_projects/mobusoperandi.github.io/output/primary.ttf": could not read file `/home/alexander/ultron/open-source_projects/mobusoperandi.github.io/output/primary.ttf`
```
File system permissions seem fine.

**Comment by lomirus** [comment]
Hello, thanks for your feedback. But sadly I am busy now and cannot take extra time for fixing this recently. It will be in at least one or two weeks before I am available.

**Comment by lomirus** [comment]
This bug seems to be easier than what I thought and it has been fixed just now. The reason is that live-server can not even read the local binary assets and no one noticed this problem until now 👀
